### PR TITLE
Add support for milliseconds.

### PR DESCRIPTION
**Pull request by TheGuardianWolf**

### CODE REVIEW

**Comment by framp** [comment]
Thanks for the contribution! @TheGuardianWolf 

Do you mind adding some tests around milliseconds in here? 
https://github.com/framp/juration/blob/master/test/index.html

**Comment by TheGuardianWolf** [comment]
I'll have a go after I complete my current project, I'm currently using this fork of juration for a node utility. I'm not 100% sure the use of floats is bug free at the moment. Also, there seems to be commits ahead on the master involving customization units for stringify?

That gives me two thoughts. How easy is it to merge with the master repository from this one? And is it possible to have 'plugin' style units instead of having them hardcoded? Potentially even microseconds could be useful.

**Comment by TheGuardianWolf** [comment]
I've written the tests in my fork, however there seems to be a bug with any millisecond time ending in 3, and I can't seem to figure out why (see the tests).

This might have to do with the use of floats, so perhaps I should rebase the system around millisecond times instead of seconds. However, this creates even more issues with chrono time etc.

**Comment by framp** [comment]
Merging with master is quite easy, I have a branch which is almost there.

That bug looks very peculiar, I'll have a look this weekend

**Comment by framp** [comment]
@TheGuardianWolf:
The problem turned out to be related to the usual IEEE 754 handling of floating point number.
I just added a Math.round(*1000)/1000 which should cover the ms scenario and published with your changes. Thanks again for the contribution!
I also pulled the new changes from the master repo (which is not node friendly).

I had a look at the code and there is a lot I don't like.
I'm not using juration in production but I'll try to squeeze a API compatible rewrite asap.

**Comment by TheGuardianWolf** [comment]
Alright, thanks for the help with that. I'd have never found that issue. I'm done with the project so I'll switch over the dependency back to this and lock it at that version number for now.

Should I keep my fork or can I delete that? I'm not entirely sure how it works.

**Comment by framp** [comment]
Feel free to delete it or keep it, it won't influence this repo.

**Pull request merged**
